# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate objective value.
#'
#' @param params A vector of starting weights b1,b2,...,bm,theta11,theta12,...theta1m, ...theta p 1,...,theta p m
#' @param yval A matrix of indicators of death
#' @param featureValue A matrix of feature values.
#' @param C1 The regularization term.
#' @param delta The event status indicator (1= death, 0 = censored), sorted.
#' @export
mtlr_objVal <- function(params, yval, featureValue, C1, delta) {
    .Call('_MTLR_mtlr_objVal', PACKAGE = 'MTLR', params, yval, featureValue, C1, delta)
}

#' Calculate Gradient
#'
#' @inheritParams mtlr_objVal
#' @export
mtlr_grad <- function(params, yval, featureValue, C1, delta) {
    .Call('_MTLR_mtlr_grad', PACKAGE = 'MTLR', params, yval, featureValue, C1, delta)
}

#' Predict survival curves.
#'
#'@inheritParams mtlr_objVal
#' @export
mtlr_predict <- function(params, featureValue) {
    .Call('_MTLR_mtlr_predict', PACKAGE = 'MTLR', params, featureValue)
}

